name: CI Pipeline

on:
  pull_request:
    branches:
      - CI/CD_branch 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser Type'
        required: true
        default: 'Chrome'
        type: choice
        options: 
          - 'Chrome'
          - 'Firefox'
          - 'Edge'
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'CI/CD_branch'

jobs:
  build-and-test:
    name: Build and Tests
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: ${{ github.event.inputs.branch }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: .

    - name: Build
      run: dotnet build --no-restore
      working-directory: .

    - name: Run API tests
      run: dotnet test --filter "Category=API" --logger "trx;LogFileName=API_TestResults.trx"
      working-directory: ./SeleniumWebDriverTask.Tests/SeleniumWebDriverTask.Tests.TestsAPI
      continue-on-error: true

    - name: Run UI Tests
      run: dotnet test --filter "Category=UI" --logger "trx;LogFileName=UI_TestResults.trx"
      working-directory: ./SeleniumWebDriverTask.Tests/SeleniumWebDriverTask.Tests.Tests
      continue-on-error: true
      
    - name: Run SpecFlow Tests
      run: dotnet test ./SeleniumWebDriverTask.Tests/SeleniumWebDriverTask.Spec/SeleniumWebDriverTask.Spec.csproj --logger "trx;LogFileName=SpecFlow_SpecFlow_TestResults.trx"
 
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
          name: TestResults
          path: |
            **/*.trx
            TestResults
          if: always()

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/TestResults
          **/Screenshots
          **/*.trx
