name: CI Pipeline

on:
  pull_request:
    branches:
      - CI/CD_branch 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser Type'
        required: true
        default: 'Chrome'
        type: choice
        options: 
          - 'Chrome'
          - 'Firefox'
          - 'Edge'
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'CI/CD_branch'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
          
      - name: Run API Tests
        run: dotnet test --filter "Category=API" --logger "trx;LogFileName=API_TestResults.trx"
        continue-on-error: true

      - name: Run UI Tests
        run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=UI_TestResults.trx"

      - name: Check if Tests Failed
        run: |
          if ($LASTEXITCODE -ne 0) { echo "TEST_FAILED=true" >> $env:GITHUB_ENV }

      - name: Check if Screenshots directory exists
        run: |
          if (Test-Path "${{ github.workspace }}\Screenshots") {
            echo "DIR_EXISTS=true" >> $env:GITHUB_ENV
          }

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ${{ github.workspace }}/TestResults/*.trx

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: env.DIR_EXISTS == 'true' && env.TEST_FAILED == 'true'
        with:
          name: screenshots
          path: ${{ github.workspace }}/Screenshots
