name: CI Pipeline

on:
  pull_request:
    branches:
      - CI/CD_branch 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser Type'
        required: true
        default: 'Chrome'
        type: choice
        options: 
          - 'Chrome'
          - 'Firefox'
          - 'Edge'
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'CI/CD_branch'

jobs:
  build-and-test:
    name: Build and Tests
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: .

    - name: Build
      run: dotnet build --no-restore
      working-directory: .

    - name: Run API Tests
      run: dotnet test SeleniumWebDriverTask.Tests/SeleniumWebDriverTask.Tests.csproj --filter Category=API --no-build
      working-directory:  .

    - name: Run UI Tests
      if: always()
      run: dotnet test SeleniumWebDriverTask.Tests --filter Category=Tests --no-build
      env:
        BROWSER: ${{ github.event.inputs.browser || 'chrome' }}
      working-directory: .

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/TestResults
          **/Screenshots
          **/*.trx
