name: CI Pipeline

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser Type'
        required: true
        default: 'Chrome'
        type: choice
        options: 
          - 'Chrome'
          - 'Firefox'
          - 'Edge'
    
jobs:
  build-and-test:
    name: Build and Tests
    runs-on: windows-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
          ref: CI/CD_branch

     - name: Setup .NET
       uses: actions/setup-dotnet@v1
       with:
          dotnet-version: '8.0'
          
     - name: Restore Dependencies
       run: dotnet restore
        
     - name: Run API tests
       run: dotnet test --filter "Category=API" --logger "trx;LogFileName=API_TestResults.trx"
       continue-on-error: true
        
     - name: Run UI Tests (SpecFlow and Traditional Tests)
       run: |
          dotnet test --filter TestCategory=TestFilter --logger "trx;LogFileName=SpecFlow_UI_TestResults.trx"
          dotnet test --filter "FullyQualifiedName~Tests.TestsEpamPage" --logger "trx;LogFileName=UI_TestResults.trx"
       continue-on-error: true
       env:
           HEADLESS: ${{ github.event.inputs.headless || 'true' }}
           
     - name: Publish Test Results
       if: always()
       uses: actions/upload-artifact@v4
       with:
        name: test-results
        path: |
         **/TestResults
         **/*.trx

     - name: Upload Screenshot Artifact 
       if: always()  # Zawsze próbuj załączyć zrzuty ekranu
       uses: actions/upload-artifact@v4
       with:
        name: failure-screenshot
        path: '**/Screenshots/*.png'
        if-no-files-found: ignore
