name: CI Pipeline

on:
  pull_request:
    branches:
      - CI/CD_branch 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser Type'
        required: true
        default: 'Chrome'
        type: choice
        options: 
          - 'Chrome'
          - 'Firefox'
          - 'Edge'
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'CI/CD_branch'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
          
      - name: Run API Tests
        run: dotnet test --filter "Category=API" --logger "trx;LogFileName=API_TestResults.trx"
        continue-on-error: true

      - name: Run tests in parallel
        run: dotnet test --filter "FullyQualifiedName~MyNamespace.AlphabeticalTests"
        continue-on-error: true
        
      - name: Run SpecFlow tests
        run: dotnet test SeleniumWebDriverTask.Tests.Spec --no-build
 
      - name: Check if Tests Failed
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
          if ($LASTEXITCODE -ne 0) { echo "TEST_FAILED=true" >> $env:GITHUB_ENV }
      
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
         name: dotnet-results-${{ matrix.dotnet-version }}
         path: TestResults-${{ matrix.dotnet-version }}
         if: always()
         
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: env.DIR_EXISTS == 'true' && env.TEST_FAILED == 'true'
        with:
          name: screenshots
          path: ${{ github.workspace }}/Screenshots 
